// Package integration is a black-box end-to-end test: it builds the real
// cli binary and every V1 plugin, runs `lumo new` non-interactively,
// and verifies the generated project actually builds and passes its own
// tests, per ADR-0004's quality bar. It has no import dependency on
// core/sdk — it only shells out to `go build` and the built binaries,
// exactly as a real user would.
package integration

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root, err := filepath.Abs(filepath.Join(wd, "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func exeName(base string) string {
	if runtime.GOOS == "windows" {
		return base + ".exe"
	}
	return base
}

func buildBinary(t *testing.T, root, pkgDir, outPath string) {
	t.Helper()
	cmd := exec.Command("go", "build", "-o", outPath, "./"+pkgDir)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build ./%s: %v\n%s", pkgDir, err, out)
	}
}

func copyFile(t *testing.T, src, dst string) {
	t.Helper()
	data, err := os.ReadFile(src)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(dst, data, 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestEndToEndGenerateGoRestAPI builds the whole system fresh and proves
// the V1 promise: lumo new -> a working, tested Go REST API project
// with all three capabilities applied.
func TestEndToEndGenerateGoRestAPI(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "go-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/go-rest-api", filepath.Join(templateDir, exeName("go-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	capabilitiesDir := filepath.Join(bin, "plugins", "builtin")
	for _, cap := range []string{"git-init", "readme", "github-actions-ci"} {
		d := filepath.Join(capabilitiesDir, cap)
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
		buildBinary(t, root, "plugins/builtin/"+cap, filepath.Join(d, exeName(cap)))
		copyFile(t, filepath.Join(root, "plugins", "builtin", cap, "plugin.json"), filepath.Join(d, "plugin.json"))
	}

	genParent := t.TempDir()
	const projectName = "e2e-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "go",
		"--framework", "rest-api",
		"--capabilities", "git-init,readme,github-actions-ci",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates")+string(os.PathListSeparator)+capabilitiesDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{
		"go.mod", "main.go",
		filepath.Join("internal", "http", "router.go"),
		filepath.Join("internal", "http", "router_test.go"),
		"Makefile", "README.md", ".gitignore",
		".git",
		filepath.Join(".github", "workflows", "ci.yml"),
	}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	readme, err := os.ReadFile(filepath.Join(projectDir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(readme), "Generated by [Lumo]") {
		t.Errorf("README.md missing the readme-capability footer:\n%s", readme)
	}

	buildCmd := exec.Command("go", "build", "./...")
	buildCmd.Dir = projectDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated project failed to build: %v\n%s", err, out)
	}

	testCmd := exec.Command("go", "test", "./...")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated project failed its own tests: %v\n%s", err, out)
	}

	logCmd := exec.Command("git", "log", "--oneline")
	logCmd.Dir = projectDir
	out, err := logCmd.CombinedOutput()
	if err != nil || strings.TrimSpace(string(out)) == "" {
		t.Fatalf("expected git-init to have created a commit: %v\n%s", err, out)
	}
}

// TestWizardLineFallbackGeneratesProject drives the wizard itself end
// to end: piped stdin means no TTY, so it exercises the numbered-list
// line fallback (ADR-0007) with menus built from discovery — the
// registry-driven wizard (project type → language → framework →
// capabilities, each filtered by the previous answer). This proves the
// wizard path, not just the flags path, generates a real project.
func TestWizardLineFallbackGeneratesProject(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "go-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/go-rest-api", filepath.Join(templateDir, exeName("go-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	capabilitiesDir := filepath.Join(bin, "plugins", "builtin")
	for _, cap := range []string{"git-init", "readme"} {
		d := filepath.Join(capabilitiesDir, cap)
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
		buildBinary(t, root, "plugins/builtin/"+cap, filepath.Join(d, exeName(cap)))
		copyFile(t, filepath.Join(root, "plugins", "builtin", cap, "plugin.json"), filepath.Join(d, "plugin.json"))
	}

	genParent := t.TempDir()
	const projectName = "wizard-demo"

	answers := strings.Join([]string{
		projectName,       // project name
		genParent,         // location (always asked — never the CWD/exe dir)
		"default",         // theme
		"backend-service", // project type
		"go",              // language
		"rest-api",        // framework
		"git-init,readme", // capabilities
	}, "\n") + "\n"

	cmd := exec.Command(cliPath, "new")
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates")+string(os.PathListSeparator)+capabilitiesDir)
	cmd.Stdin = strings.NewReader(answers)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("lumo new via piped wizard failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)
	for _, f := range []string{"go.mod", "main.go", "README.md", ".git"} {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}
}

// TestWizardNoTemplatesFailsFast proves the registry-driven wizard
// degrades honestly: with no template plugins discoverable, the wizard
// refuses to ask dead-end questions and exits with a clear error.
func TestWizardNoTemplatesFailsFast(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	// Point LUMO_PLUGIN_DIRS at an empty directory — discovery finds no
	// templates at all, and the embedded fallback must not engage (an
	// explicit override always wins, ADR-0012).
	empty := t.TempDir()

	cmd := exec.Command(cliPath, "new")
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+empty)
	cmd.Stdin = strings.NewReader("some-project\n")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("lumo new with no templates should fail, got success\n%s", out)
	}
	if !strings.Contains(string(out), "no template plugins found") {
		t.Errorf("expected a clear no-templates error, got:\n%s", out)
	}
}

// TestEndToEndGenerateNodeRestAPI is the cross-language proof: the same
// pipeline (lumo new -> a real, tested project), but for V1's
// second template, a genuinely different language. No npm install step
// on purpose — the generated project has zero npm dependencies, so
// `npm test` passing with no install first is itself part of the proof.
func TestEndToEndGenerateNodeRestAPI(t *testing.T) {
	if _, err := exec.LookPath("npm"); err != nil {
		t.Skip("npm not found on PATH — skipping (see .github/workflows/ci.yml for the CI Node.js setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "node-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/node-rest-api", filepath.Join(templateDir, exeName("node-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "node-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-node-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "node",
		"--framework", "http-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{"package.json", "server.js", "server.test.js", "README.md", ".gitignore"}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	testCmd := exec.Command("npm", "test")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Node project failed its own tests: %v\n%s", err, out)
	}
}

// TestEndToEndGenerateTypeScriptRestAPI mirrors
// TestEndToEndGenerateNodeRestAPI: same zero-npm-install philosophy,
// but the generated source is TypeScript, run directly via Node's
// built-in type stripping (see templates/typescript-rest-api/main.go).
func TestEndToEndGenerateTypeScriptRestAPI(t *testing.T) {
	if _, err := exec.LookPath("npm"); err != nil {
		t.Skip("npm not found on PATH — skipping (see .github/workflows/ci.yml for the CI Node.js setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "typescript-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/typescript-rest-api", filepath.Join(templateDir, exeName("typescript-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "typescript-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-typescript-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "typescript",
		"--framework", "http-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{"package.json", "tsconfig.json", "server.ts", "server.test.ts", "README.md", ".gitignore"}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	testCmd := exec.Command("npm", "test")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated TypeScript project failed its own tests: %v\n%s", err, out)
	}
}

// TestEndToEndGenerateRustRestAPI proves the Rust template (std-only,
// no crates.io fetch) actually builds and passes its own tests.
func TestEndToEndGenerateRustRestAPI(t *testing.T) {
	if _, err := exec.LookPath("cargo"); err != nil {
		t.Skip("cargo not found on PATH — skipping (see .github/workflows/ci.yml for the CI Rust setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "rust-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/rust-rest-api", filepath.Join(templateDir, exeName("rust-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "rust-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-rust-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "rust",
		"--framework", "http-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{"Cargo.toml", filepath.Join("src", "main.rs"), "README.md", ".gitignore"}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	testCmd := exec.Command("cargo", "test")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Rust project failed its own tests: %v\n%s", err, out)
	}
}

// makeCommand returns the first available make implementation on PATH
// — plain "make" on Linux/macOS/CI, "mingw32-make" on a Windows dev
// machine where MinGW ships make under that name instead — or "" if
// neither is found.
func makeCommand() string {
	for _, name := range []string{"make", "mingw32-make"} {
		if _, err := exec.LookPath(name); err == nil {
			return name
		}
	}
	return ""
}

// TestEndToEndGenerateCppCLI proves the C++ template (plain Makefile +
// g++ -std=c++14, no CMake, no extra deps) actually builds and passes
// its own tests.
func TestEndToEndGenerateCppCLI(t *testing.T) {
	make := makeCommand()
	if make == "" {
		t.Skip("no make/mingw32-make found on PATH — skipping")
	}
	if _, err := exec.LookPath("g++"); err != nil {
		t.Skip("g++ not found on PATH — skipping (see .github/workflows/ci.yml for the CI C++ toolchain)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "cpp-cli")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/cpp-cli", filepath.Join(templateDir, exeName("cpp-cli")))
	copyFile(t, filepath.Join(root, "templates", "cpp-cli", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-cpp-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "cli-tool",
		"--language", "cpp",
		"--framework", "cli",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{
		"Makefile", filepath.Join("include", "calc.hpp"),
		filepath.Join("src", "calc.cpp"), filepath.Join("src", "main.cpp"),
		filepath.Join("test", "test_main.cpp"), "README.md", ".gitignore",
	}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	buildCmd := exec.Command(make, "build")
	buildCmd.Dir = projectDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated C++ project failed to build: %v\n%s", err, out)
	}

	testCmd := exec.Command(make, "test")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated C++ project failed its own tests: %v\n%s", err, out)
	}
}

// pythonCommand returns the first working Python 3 interpreter on
// PATH — "python3" (the common name on Linux/macOS/CI) or "python"
// (common on Windows) — or "" if neither actually runs. Checks more
// than LookPath: on Windows, "python"/"python3" can resolve to the App
// Execution Alias stub (a real PATH entry that prints a Microsoft
// Store prompt and exits non-zero instead of running anything) when no
// real interpreter is installed, so a plain LookPath success is not
// sufficient evidence of a usable interpreter.
func pythonCommand() string {
	for _, name := range []string{"python3", "python"} {
		if exec.Command(name, "--version").Run() == nil {
			return name
		}
	}
	return ""
}

// TestEndToEndGeneratePythonRestAPI proves the Python template (stdlib
// http.server/unittest, zero pip installs) actually runs its own test
// suite. NOT LOCALLY VERIFIED where this test was written (no working
// Python interpreter was available — see
// templates/python-rest-api/main.go) — this LookPath-guarded skip
// means the first real run of this test is CI.
func TestEndToEndGeneratePythonRestAPI(t *testing.T) {
	python := pythonCommand()
	if python == "" {
		t.Skip("no python3/python found on PATH — skipping (see .github/workflows/ci.yml for the CI Python setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "python-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/python-rest-api", filepath.Join(templateDir, exeName("python-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "python-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-python-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "python",
		"--framework", "http-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{"server.py", "test_server.py", "README.md", ".gitignore"}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	testCmd := exec.Command(python, "-m", "unittest", "discover")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Python project failed its own tests: %v\n%s", err, out)
	}
}

// javaToolchainAvailable reports whether both javac and java actually
// run (not just resolve on PATH — see pythonCommand's comment for why
// that distinction matters on Windows).
func javaToolchainAvailable() bool {
	return exec.Command("javac", "-version").Run() == nil && exec.Command("java", "-version").Run() == nil
}

// TestEndToEndGenerateJavaRestAPI proves the Java template
// (com.sun.net.httpserver + java.net.http, no Maven) actually builds
// and passes its own tests. NOT LOCALLY VERIFIED where this test was
// written (no JDK was available — see
// templates/java-rest-api/main.go) — this guarded skip means the
// first real run of this test is CI.
func TestEndToEndGenerateJavaRestAPI(t *testing.T) {
	if !javaToolchainAvailable() {
		t.Skip("javac/java not found on PATH — skipping (see .github/workflows/ci.yml for the CI Java setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "java-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/java-rest-api", filepath.Join(templateDir, exeName("java-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "java-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-java-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "java",
		"--framework", "http-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{filepath.Join("src", "Server.java"), filepath.Join("src", "ServerTest.java"), "README.md", ".gitignore"}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	outDir := filepath.Join(projectDir, "out")
	buildCmd := exec.Command("javac", "-d", outDir, filepath.Join("src", "Server.java"), filepath.Join("src", "ServerTest.java"))
	buildCmd.Dir = projectDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Java project failed to build: %v\n%s", err, out)
	}

	testCmd := exec.Command("java", "-cp", outDir, "ServerTest")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Java project failed its own tests: %v\n%s", err, out)
	}
}

// TestEndToEndGenerateKotlinCLI proves the Kotlin template (plain
// kotlinc, no Gradle) actually builds and passes its own tests. NOT
// LOCALLY VERIFIED where this test was written (no Kotlin compiler
// was available — see templates/kotlin-cli/main.go) — this guarded
// skip means the first real run of this test is CI.
func TestEndToEndGenerateKotlinCLI(t *testing.T) {
	if exec.Command("kotlinc", "-version").Run() != nil {
		t.Skip("kotlinc not found on PATH — skipping (see .github/workflows/ci.yml for the CI Kotlin setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "kotlin-cli")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/kotlin-cli", filepath.Join(templateDir, exeName("kotlin-cli")))
	copyFile(t, filepath.Join(root, "templates", "kotlin-cli", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-kotlin-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "cli-tool",
		"--language", "kotlin",
		"--framework", "cli",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{
		filepath.Join("src", "Calc.kt"), filepath.Join("src", "Main.kt"),
		filepath.Join("test", "CalcTest.kt"), "README.md", ".gitignore",
	}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	testJar := filepath.Join(projectDir, "test.jar")
	buildCmd := exec.Command("kotlinc", filepath.Join("src", "Calc.kt"), filepath.Join("test", "CalcTest.kt"), "-include-runtime", "-d", testJar)
	buildCmd.Dir = projectDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Kotlin project failed to build: %v\n%s", err, out)
	}

	testCmd := exec.Command("java", "-jar", testJar)
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated Kotlin project failed its own tests: %v\n%s", err, out)
	}
}

// TestEndToEndGenerateCSharpRestAPI proves the C# template
// (System.Net.HttpListener, no ASP.NET Core, no NuGet packages)
// actually builds and passes its own tests. NOT LOCALLY VERIFIED
// where this test was written (no working .NET SDK was available —
// see templates/csharp-rest-api/main.go) — this guarded skip means
// the first real run of this test is CI.
func TestEndToEndGenerateCSharpRestAPI(t *testing.T) {
	if exec.Command("dotnet", "--version").Run() != nil {
		t.Skip("dotnet not found/working on PATH — skipping (see .github/workflows/ci.yml for the CI .NET setup)")
	}

	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "csharp-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/csharp-rest-api", filepath.Join(templateDir, exeName("csharp-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "csharp-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	genParent := t.TempDir()
	const projectName = "e2e-csharp-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "csharp",
		"--framework", "http-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{"Server.csproj", "Program.cs", "README.md", ".gitignore"}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	testCmd := exec.Command("dotnet", "run", "--", "test")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated C# project failed its own tests: %v\n%s", err, out)
	}
}

// TestEndToEndGenerateViaEmbeddedFallback proves the actual claim behind
// ADR-0012: a lumo binary with no sibling templates/plugins
// directories at all — exactly what `go install` produces — still
// works, via the V1 plugin set embedded into the binary at build time
// (cli/internal/embedded) and self-extracted on first use. This test
// stages real plugin binaries into cli/internal/embedded/assets/ (the
// same directory the Makefile and release.yml stage into) so `go build
// ./cli` actually embeds them, then runs the resulting binary from a
// directory that has nothing next to it and no LUMO_PLUGIN_DIRS —
// unlike TestEndToEndGenerateGoRestAPI, which deliberately sets
// LUMO_PLUGIN_DIRS and exercises the normal sibling-directory path.
func TestEndToEndGenerateViaEmbeddedFallback(t *testing.T) {
	root := repoRoot(t)
	embedAssets := filepath.Join(root, "cli", "internal", "embedded", "assets")

	stageEmbedded(t, root, embedAssets)

	bin := t.TempDir()
	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	// A bare directory: no templates/, no plugins/, no LUMO_PLUGIN_DIRS.
	// This is the go-install scenario, reproduced without needing a
	// real `go install` from the public module path.
	genParent := t.TempDir()
	const projectName = "e2e-embedded-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "go",
		"--framework", "rest-api",
		"--capabilities", "readme",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = envWithout(os.Environ(), "LUMO_PLUGIN_DIRS")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("lumo new via embedded fallback failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)
	for _, f := range []string{"go.mod", "main.go", "README.md"} {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}
}

// TestPluginsValidateCommand proves the pre-release extension check:
// `lumo plugins validate <dir>` accepts a real, built plugin (the
// binary passes the plugin.initialize identity/protocol cross-check),
// and rejects both a manifest whose binary doesn't match it (tampered
// name -> IdentityMismatchError) and an invalid manifest — the same
// fail-fast surface `new` uses, without generating anything.
func TestPluginsValidateCommand(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	pluginDir := filepath.Join(bin, "plugins", "go-rest-api")
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/go-rest-api", filepath.Join(pluginDir, exeName("go-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(pluginDir, "plugin.json"))

	runValidate := func(t *testing.T, dir string) (string, error) {
		t.Helper()
		cmd := exec.Command(cliPath, "plugins", "validate", dir)
		out, err := cmd.CombinedOutput()
		return string(out), err
	}

	if out, err := runValidate(t, pluginDir); err != nil {
		t.Fatalf("validate on a real plugin should exit 0, got err=%v\n%s", err, out)
	}

	// A real identity mismatch requires the spawned binary to report a
	// different name than the manifest the registry reads. That happens
	// when the entrypoint is a nested path whose directory carries its
	// own plugin.json: the top-level manifest declares "go-rest-api"
	// with entrypoint "./inner/go-rest-api", but the binary at that
	// path reads the manifest beside itself (inner/plugin.json, name
	// "inner-plugin") and self-reports differently — the stale- or
	// swapped-binary shape ADR-0008's cross-check exists to catch.
	mismatch := filepath.Join(bin, "mismatch")
	inner := filepath.Join(mismatch, "inner")
	if err := os.MkdirAll(inner, 0o755); err != nil {
		t.Fatal(err)
	}
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(mismatch, "plugin.json"))
	outer, err := os.ReadFile(filepath.Join(mismatch, "plugin.json"))
	if err != nil {
		t.Fatal(err)
	}
	nested := strings.Replace(string(outer), `"./go-rest-api"`, `"./inner/go-rest-api"`, 1)
	if nested == string(outer) {
		t.Fatal("test setup: could not rewrite the entrypoint field")
	}
	if err := os.WriteFile(filepath.Join(mismatch, "plugin.json"), []byte(nested), 0o644); err != nil {
		t.Fatal(err)
	}
	innerManifest := strings.Replace(string(outer), `"go-rest-api"`, `"inner-plugin"`, 1)
	if err := os.WriteFile(filepath.Join(inner, "plugin.json"), []byte(innerManifest), 0o644); err != nil {
		t.Fatal(err)
	}
	copyFile(t, filepath.Join(pluginDir, exeName("go-rest-api")), filepath.Join(inner, exeName("go-rest-api")))
	if out, err := runValidate(t, mismatch); err == nil {
		t.Fatalf("validate on a binary/manifest identity mismatch should fail, got exit 0\n%s", out)
	}

	invalid := filepath.Join(bin, "invalid")
	if err := os.MkdirAll(invalid, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(invalid, "plugin.json"), []byte(`{"protocolVersion": "1"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := runValidate(t, invalid); err == nil {
		t.Fatalf("validate on an invalid manifest should fail, got exit 0\n%s", out)
	}
}

// TestGithubActionsCIRefusesNonGoProject pins the language gate: the
// capability writes a Go-only workflow, so selecting it for a Node
// project must fail with a clear error — before the workflow file is
// written — rather than silently generating a CI config that can never
// be green.
func TestGithubActionsCIRefusesNonGoProject(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "node-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/node-rest-api", filepath.Join(templateDir, exeName("node-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "node-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	capDir := filepath.Join(bin, "plugins", "builtin", "github-actions-ci")
	if err := os.MkdirAll(capDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "plugins/builtin/github-actions-ci", filepath.Join(capDir, exeName("github-actions-ci")))
	copyFile(t, filepath.Join(root, "plugins", "builtin", "github-actions-ci", "plugin.json"), filepath.Join(capDir, "plugin.json"))

	genParent := t.TempDir()
	cmd := exec.Command(cliPath, "new", "node-ci-demo",
		"--project-type", "backend-service",
		"--language", "node",
		"--framework", "http-api",
		"--capabilities", "github-actions-ci",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "LUMO_PLUGIN_DIRS="+filepath.Join(bin, "templates")+string(os.PathListSeparator)+filepath.Join(bin, "plugins", "builtin"))
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
		t.Fatalf("got err=%v, want exit code 1\n%s", err, out)
	}
	if !strings.Contains(string(out), "only supports Go") {
		t.Errorf("error should explain the Go-only gate, got:\n%s", out)
	}
	// The template still generated (generation happens before apply), but
	// the workflow file must not exist.
	projectDir := filepath.Join(genParent, "node-ci-demo")
	if _, statErr := os.Stat(filepath.Join(projectDir, "package.json")); statErr != nil {
		t.Errorf("project should have been generated before the capability gate fired: %v", statErr)
	}
	if _, statErr := os.Stat(filepath.Join(projectDir, ".github", "workflows", "ci.yml")); statErr == nil {
		t.Error("ci.yml must not be written for a non-Go project")
	}
}

// stageEmbedded builds the V1 template/capability binaries and copies
// them (plus their plugin.json manifests) into embedAssets, mirroring
// exactly what the Makefile's stage-embedded target and release.yml's
// per-target staging step do. It registers a cleanup that removes the
// staged content afterward, regardless of test outcome, so the repo's
// working tree is left exactly as it was found (only the checked-in
// assets/.gitkeep survives).
func stageEmbedded(t *testing.T, root, embedAssets string) {
	t.Helper()
	t.Cleanup(func() {
		os.RemoveAll(filepath.Join(embedAssets, "templates"))
		os.RemoveAll(filepath.Join(embedAssets, "plugins"))
	})

	templateDir := filepath.Join(embedAssets, "templates", "go-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/go-rest-api", filepath.Join(templateDir, exeName("go-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	capDir := filepath.Join(embedAssets, "plugins", "builtin", "readme")
	if err := os.MkdirAll(capDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "plugins/builtin/readme", filepath.Join(capDir, exeName("readme")))
	copyFile(t, filepath.Join(root, "plugins", "builtin", "readme", "plugin.json"), filepath.Join(capDir, "plugin.json"))
}

// envWithout returns env with every entry whose key matches name
// removed — used so the embedded-fallback test can't accidentally
// inherit a LUMO_PLUGIN_DIRS set in the ambient test environment (e.g.
// by a developer running tests locally with it exported).
func envWithout(env []string, name string) []string {
	prefix := name + "="
	out := make([]string, 0, len(env))
	for _, e := range env {
		if strings.HasPrefix(e, prefix) {
			continue
		}
		out = append(out, e)
	}
	return out
}

// buildCLI builds the lumo binary alone (no plugin dirs) — enough
// for the argument-parsing and pre-registry guard tests below, which
// fail before any plugin discovery matters.
func buildCLI(t *testing.T, root string) string {
	t.Helper()
	bin := t.TempDir()
	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)
	return cliPath
}

// TestBareLumoRunsTheWizard pins the no-arguments routing: bare
// `lumo` (what double-clicking the binary does) must enter the
// wizard, not print help and exit. With piped stdin there's no TTY, so
// the wizard's line fallback reads EOF and fails with "project name is
// required" (exit 1) — this test pins that routing so a regression can't
// silently return to the "prints help, closes instantly" behavior. A
// real template directory sits next to the binary so the registry-driven
// wizard has something discoverable and reaches the project-name prompt.
func TestBareLumoRunsTheWizard(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()
	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "go-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/go-rest-api", filepath.Join(templateDir, exeName("go-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	cmd := exec.Command(cliPath)
	cmd.Dir = t.TempDir()
	cmd.Stdin = strings.NewReader("")
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
		t.Fatalf("got err=%v, want exit code 1 (wizard EOF path)\n%s", err, out)
	}
	if !strings.Contains(string(out), "project name is required") {
		t.Errorf("bare lumo should have entered the wizard and failed on EOF, got:\n%s", out)
	}
	if strings.Contains(string(out), "usage: lumo") {
		t.Errorf("bare lumo should not print the help text anymore, got:\n%s", out)
	}
}

// TestNewRejectsExtraPositionalArguments: `lumo new` takes at most
// one positional (the project name). Anything more is a usage error,
// not something to silently ignore — and it must be caught before any
// plugin discovery, generation, or filesystem side effect.
func TestNewRejectsExtraPositionalArguments(t *testing.T) {
	cliPath := buildCLI(t, repoRoot(t))

	cmd := exec.Command(cliPath, "new", "demo", "stray-arg")
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 2 {
		t.Fatalf("got err=%v, want exit code 2 (usage error)\n%s", err, out)
	}
	if !strings.Contains(string(out), "stray-arg") {
		t.Errorf("stderr should name the offending argument, got:\n%s", out)
	}
}

// TestNewRejectsAnswersFileCombinedWithPositional: the project name
// belongs in the answers file when --answers is given; combining both
// is ambiguous and must be rejected up front (exit 2), even if the
// answers file itself doesn't exist yet.
func TestNewRejectsAnswersFileCombinedWithPositional(t *testing.T) {
	cliPath := buildCLI(t, repoRoot(t))

	cmd := exec.Command(cliPath, "new", "demo", "--answers", filepath.Join(t.TempDir(), "missing.txt"))
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 2 {
		t.Fatalf("got err=%v, want exit code 2 (usage error)\n%s", err, out)
	}
}

// TestNewRefusesNonEmptyTargetDirectory: plugins write files
// unconditionally, so generating into an existing non-empty directory
// would silently overwrite — the guard must refuse before any plugin
// runs (it needs no plugin dirs at all to trigger).
func TestNewRefusesNonEmptyTargetDirectory(t *testing.T) {
	cliPath := buildCLI(t, repoRoot(t))

	genParent := t.TempDir()
	existing := filepath.Join(genParent, "taken")
	if err := os.MkdirAll(existing, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(existing, "keep.txt"), []byte("mine"), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(cliPath, "new", "taken",
		"--project-type", "backend-service",
		"--language", "go",
		"--framework", "rest-api",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
		t.Fatalf("got err=%v, want exit code 1\n%s", err, out)
	}
	if !strings.Contains(string(out), "not empty") {
		t.Errorf("error should explain the directory is not empty, got:\n%s", out)
	}
	// The existing file must be untouched.
	data, readErr := os.ReadFile(filepath.Join(existing, "keep.txt"))
	if readErr != nil || string(data) != "mine" {
		t.Errorf("existing file was modified: data=%q err=%v", data, readErr)
	}
}

// TestNewRejectsUnknownTheme: an invalid --theme must fail validation
// with a clear error (exit 1), not silently fall back to "default".
func TestNewRejectsUnknownTheme(t *testing.T) {
	cliPath := buildCLI(t, repoRoot(t))

	cmd := exec.Command(cliPath, "new", "demo",
		"--project-type", "backend-service",
		"--language", "go",
		"--framework", "rest-api",
		"--theme", "neon",
	)
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
		t.Fatalf("got err=%v, want exit code 1\n%s", err, out)
	}
	if !strings.Contains(string(out), "unknown theme") {
		t.Errorf("error should mention the unknown theme, got:\n%s", out)
	}
}

// isolatedConfigEnv returns an environment (based on os.Environ()) with
// the OS's per-user config-directory variable (%AppData% on Windows,
// $XDG_CONFIG_HOME elsewhere — matching os.UserConfigDir() and
// cli/internal/prompt/config_test.go's withTempConfigDir) redirected to
// dir, so a subprocess's prompt.LoadConfig/SaveConfig calls never
// read or write the real host's %AppData%\lumo\ (or ~/.config/lumo/)
// directory during a test.
func isolatedConfigEnv(dir string) []string {
	env := os.Environ()
	if runtime.GOOS == "windows" {
		return append(env, "AppData="+dir)
	}
	return append(env, "XDG_CONFIG_HOME="+dir)
}

// TestStatusOfflineShowsRepoAndGitOnly builds the real lumo binary and
// runs `lumo status --offline` in a fresh temp directory (no .git),
// proving the Project/Git rows render and the GitHub/SonarQube rows
// report "offline" without any network call. cmd.Env is redirected via
// isolatedConfigEnv so the subprocess's prompt.LoadConfig call can never
// touch the real host's Lumo config directory (see this task's
// host-safety note: --offline still calls prompt.LoadConfig, just not
// secretstore.New(), so the config directory still needs isolating even
// though the secret store never gets touched on this path).
func TestStatusOfflineShowsRepoAndGitOnly(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()
	cliPath := filepath.Join(bin, exeName("lumo"))
	buildBinary(t, root, "cli", cliPath)

	dir := t.TempDir()
	configDir := t.TempDir()
	cmd := exec.Command(cliPath, "status", "--offline")
	cmd.Dir = dir
	cmd.Env = isolatedConfigEnv(configDir)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("lumo status --offline failed: %v\n%s", err, out)
	}
	got := string(out)
	if !strings.Contains(got, "Project:") {
		t.Errorf("output missing Project section:\n%s", got)
	}
	if !strings.Contains(got, "not initialized") {
		t.Errorf("output should report Git not initialized in a fresh temp dir:\n%s", got)
	}
	if !strings.Contains(got, "offline") {
		t.Errorf("output should mark GitHub/SonarQube as offline:\n%s", got)
	}
}

// TestConfigSetThemeRejectsUnknownTheme: `config set theme` persists a
// theme, so an unknown one must be rejected before anything is written.
func TestConfigSetThemeRejectsUnknownTheme(t *testing.T) {
	cliPath := buildCLI(t, repoRoot(t))

	cmd := exec.Command(cliPath, "config", "set", "theme", "neon")
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
		t.Fatalf("got err=%v, want exit code 1\n%s", err, out)
	}
	if !strings.Contains(string(out), "unknown theme") {
		t.Errorf("error should mention the unknown theme, got:\n%s", out)
	}
}
